# dreamreflex-csa

main:
  push:
  - stages:

    - name: 安装依赖
      image: node:20
      volumes:
        - /root/.npm
      script: npm ci

    - name: 构建打包
      image: node:20
      volumes:
        - /root/.npm
      script: |
        npm run docs:build

    - name: 部署到EdgeOne加速网络
      imports:
        - https://cnb.cool/greenshadecapital/dreamreflex/assets-secrets/-/blob/main/api-server.yml
      image: node:20
      script: npx edgeone pages deploy /workspace/.vitepress/dist/ -n dreamreflex-doc -t $EDGEONE_API_TOKEN
